Repository FTL13/FTL13, pull requests merged in 2018-04, with the labels that each got.

#3507 Add the Scarab back into normal rotation
  _maps/basemap.dm
  _maps/map_files/Scarab/Scarab.dmm
Labels: /r/titlegore, A CrAzYPiLoT Access Fuckup, A Monster860 Planet / Power Fuckup, Administration, Aetherwhisp, Approved For Merging, BYOND Issue, Balance, Bug, Cannot Reproduce, Cannot/Will Not Fix, Changes Requested, Controversial, Damn /tg/ coders..., Damn Cael Code, Do Not Merge, Duplicate, Easily Fixed, Exploit, FUCK, Feature, Feature Request, Fix, Grammar and Formatting, HONK, Help Wanted, High Priority, Inconsistency, Maintainer Label Abuse, Map Edit, Map Issue, Merge Conflict, Needs Review, Not A Bug, Not Code Merged, Not Map Merged, Oversight, PLEASE FUCKING WORK THIS TIME, Performance, Pics or it didn't happen, Port, Power cells, Refactor, Revert/Feature Removal, Runtime, SQL Change, Saved with Git Wizardry, Shuttle Issue, Sound, SpaceSHIP, Sprites, Stale, Theme / Lore Change, Trailblazer, Travis, Tweak, Upstream Inheritance, Upstream PR Merged, User Interface, WTF, Work In Progress, Working As Intended™, git rejects

#3522 Gives admins the power to force the ship to jump
  code/controllers/subsystem/starmap.dm
  code/modules/admin/admin_verbs.dm
  sound/AI/ftl_spoolup_hacked.ogg
Labels: Feature

#3533 Shield re-work
  code/__DEFINES/ship_weapons.dm
  code/_globalvars/lists/objects.dm
  code/controllers/subsystem/ships.dm
  code/datums/ftl_ships/ship_weapons.dm
  code/game/gamemodes/meteor/meteors.dm
  code/game/machinery/ftl_shieldgen.dm
  code/game/objects/structures/cannon_shell.dm
  code/modules/ftl/machinery/ftl_shieldgen.dm
  code/modules/power/management_console.dm
  ftl13.dme
  icons/effects/effects.dmi
Labels: Balance, Port, Rare floyd PR, Refactor
