Repository FTL13/FTL13, pull requests merged in 2018-06, with the labels that each got.

#3439 New pressure tank sprites, adds N2O pressure tank and adds Hydrogen skin
  code/modules/atmospherics/machinery/components/unary_devices/tank.dm
  icons/obj/atmospherics/pipes/pressure_tank.dmi
Labels: Feature, Needs Review, Sprites

#3580 Plasma glass windows fix
  code/game/objects/structures/window.dm
  icons/obj/structures.dmi
Labels: Fix

#3579 Changes random name generation to use the ship name generation
  code/__HELPERS/names.dm
Labels: Needs Review, Tweak

#3581 Feliciana:Vents fixed
  _maps/map_files/Feliciana/Feliciana.dmm
Labels: Fix, Map Edit

#3583 Plasma glass window construction fix.
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/structures/grille.dm
Labels: Fix, Needs Review
