Repository FTL13/FTL13, pull requests merged in 2019-01, with the labels that each got.

#3654 End round victory!
  code/controllers/subsystem/ticker.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/objective.dm
  code/modules/station_goals/station_goal.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
Labels: Easily Fixed, Test-Merged

#3650 Character slots and emoji parsing updated
  code/modules/client/preferences.dm
  code/modules/emoji/emoji_parse.dm
  code/modules/goonchat/browserOutput.dm
Labels: Test-Merged

#3661 Duffel bag reference changes
  code/game/objects/items/weapons/storage/backpack.dm
  icons/obj/storage.dmi
Labels: Damn /tg/ coders..., Grammar and Formatting, Sprites

#3662 Fix Butterfly, add shields to Scarab
  _maps/map_files/Butterfly/Butterfly.dmm
  _maps/map_files/Scarab/Scarab.dmm
Labels: Map Edit

#3663 Updates the requirements for mapmerge2 so that it'll work with python3.7 on Windows
  html/changelog.html
  html/changelogs/.all_changelog.yml
  tools/mapmerge2/requirements.txt
Labels: Fix
